"use client";

import { useState } from "react";
import {
  CheckSquare, Gavel, HelpCircle, Mail, Users,
  Tag, TrendingUp, Copy, Check, Download,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import ActionItems from "./ActionItems";
import Decisions from "./Decisions";
import OpenQuestions from "./OpenQuestions";
import EmailDraft from "./EmailDraft";
import { copyToClipboard, downloadAsText, getSentimentColor } from "@/lib/utils";
import type { MeetingAnalysis } from "@/types";

interface ResultsPanelProps {
  analysis: MeetingAnalysis;
}

const SENTIMENT_LABELS = {
  positive: "Positive",
  neutral: "Neutral",
  mixed: "Mixed",
  tense: "Tense",
};

export default function ResultsPanel({ analysis }: ResultsPanelProps) {
  const [copiedSummary, setCopiedSummary] = useState(false);
  const [email, setEmail] = useState(analysis.followUpEmail);

  const handleCopySummary = async () => {
    await copyToClipboard(analysis.summary);
    setCopiedSummary(true);
    setTimeout(() => setCopiedSummary(false), 2000);
  };

  const handleDownload = () => {
    const content = `# ${analysis.title}
Date: ${analysis.date}
Duration: ${analysis.duration}

## Summary
${analysis.summary}

## Attendees
${analysis.attendees?.map((a) => `- ${a.name} (${a.role})`).join("\n") ?? "Not specified"}

## Action Items
${analysis.actionItems
  .map((item, i) => `${i + 1}. [${item.priority.toUpperCase()}] ${item.task}\n   Owner: ${item.owner} | Deadline: ${item.deadline}`)
  .join("\n")}

## Decisions
${analysis.decisions.map((d, i) => `${i + 1}. ${d.decision}\n   Rationale: ${d.rationale}`).join("\n")}

## Open Questions
${analysis.openQuestions.map((q, i) => `${i + 1}. ${q.question}\n   Assigned to: ${q.assignedTo}`).join("\n")}

## Follow-Up Email
${email}

---
Generated by EchoMeet`;
    downloadAsText(content, `${analysis.title.replace(/\s+/g, "-").toLowerCase()}-echomeet.md`);
  };

  return (
    <div className="flex flex-col gap-4 h-full">
      {/* Meeting header card */}
      <div className="rounded-xl border border-border/60 bg-card p-4">
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex-1 min-w-0">
            <h2 className="font-semibold text-base leading-snug truncate">
              {analysis.title}
            </h2>
            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mt-1 text-xs text-muted-foreground">
              {analysis.date !== "Date not specified" && <span>{analysis.date}</span>}
              {analysis.duration !== "Duration not specified" && <span>· {analysis.duration}</span>}
              {analysis.attendees?.length > 0 && (
                <span className="flex items-center gap-1">
                  <Users className="h-3 w-3" />
                  {analysis.attendees.length} attendees
                </span>
              )}
            </div>
          </div>
          <div className="flex gap-1.5 flex-shrink-0">
            <Button
              variant="ghost"
              size="sm"
              className="h-7 text-xs gap-1.5 text-muted-foreground"
              onClick={handleDownload}
            >
              <Download className="h-3 w-3" />
              <span className="hidden sm:inline">Export</span>
            </Button>
          </div>
        </div>

        {/* Summary */}
        <div className="relative">
          <p className="text-sm text-muted-foreground leading-relaxed pr-6">
            {analysis.summary}
          </p>
          <button
            onClick={handleCopySummary}
            className="absolute top-0 right-0 text-muted-foreground hover:text-foreground transition-colors"
            aria-label="Copy summary"
          >
            {copiedSummary ? (
              <Check className="h-3.5 w-3.5 text-echo-400" />
            ) : (
              <Copy className="h-3.5 w-3.5" />
            )}
          </button>
        </div>

        {/* Meta chips */}
        <div className="flex flex-wrap gap-2 mt-3 pt-3 border-t border-border/40">
          {/* Sentiment */}
          <div className="flex items-center gap-1.5">
            <TrendingUp className="h-3 w-3 text-muted-foreground" />
            <span className={`text-xs font-medium ${getSentimentColor(analysis.sentiment)}`}>
              {SENTIMENT_LABELS[analysis.sentiment]} meeting
            </span>
          </div>

          {/* Key themes */}
          {analysis.keyThemes?.slice(0, 4).map((theme) => (
            <Badge key={theme} variant="outline" className="text-[10px] gap-1 h-5">
              <Tag className="h-2.5 w-2.5" />
              {theme}
            </Badge>
          ))}
        </div>

        {/* Attendees */}
        {analysis.attendees?.length > 0 && (
          <div className="mt-3 pt-3 border-t border-border/40">
            <div className="flex flex-wrap gap-1.5">
              {analysis.attendees.map((a) => (
                <div
                  key={a.name}
                  className="flex items-center gap-1.5 rounded-full bg-muted/50 border border-border/40 px-2 py-0.5"
                >
                  <div className="w-5 h-5 rounded-full bg-echo-500/20 flex items-center justify-center text-[10px] font-semibold text-echo-400">
                    {a.name.charAt(0).toUpperCase()}
                  </div>
                  <span className="text-[11px]">{a.name}</span>
                  {a.role && (
                    <span className="text-[10px] text-muted-foreground">{a.role}</span>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-3 gap-2">
        {[
          { label: "Action items", value: analysis.actionItems.length, color: "text-echo-400", icon: CheckSquare },
          { label: "Decisions", value: analysis.decisions.length, color: "text-purple-400", icon: Gavel },
          { label: "Open questions", value: analysis.openQuestions.length, color: "text-amber-400", icon: HelpCircle },
        ].map((stat) => (
          <div
            key={stat.label}
            className="rounded-lg border border-border/40 bg-card p-3 text-center"
          >
            <stat.icon className={`h-4 w-4 mx-auto mb-1 ${stat.color}`} />
            <div className={`text-xl font-bold ${stat.color}`}>{stat.value}</div>
            <div className="text-[10px] text-muted-foreground uppercase tracking-wide">{stat.label}</div>
          </div>
        ))}
      </div>

      {/* Tabbed content */}
      <Tabs defaultValue="actions" className="flex-1">
        <TabsList className="w-full grid grid-cols-4 h-9">
          <TabsTrigger value="actions" className="text-xs gap-1.5">
            <CheckSquare className="h-3 w-3" />
            <span className="hidden sm:inline">Actions</span>
            <span className="sm:hidden">Acts</span>
            {analysis.actionItems.length > 0 && (
              <span className="ml-0.5 text-[10px] bg-echo-500/20 text-echo-400 rounded-full px-1">
                {analysis.actionItems.length}
              </span>
            )}
          </TabsTrigger>
          <TabsTrigger value="decisions" className="text-xs gap-1.5">
            <Gavel className="h-3 w-3" />
            <span className="hidden sm:inline">Decisions</span>
            <span className="sm:hidden">Dec</span>
          </TabsTrigger>
          <TabsTrigger value="questions" className="text-xs gap-1.5">
            <HelpCircle className="h-3 w-3" />
            <span className="hidden sm:inline">Questions</span>
            <span className="sm:hidden">Q&amp;A</span>
          </TabsTrigger>
          <TabsTrigger value="email" className="text-xs gap-1.5">
            <Mail className="h-3 w-3" />
            Email
          </TabsTrigger>
        </TabsList>

        <TabsContent value="actions" className="mt-4">
          <ActionItems items={analysis.actionItems} />
        </TabsContent>
        <TabsContent value="decisions" className="mt-4">
          <Decisions decisions={analysis.decisions} />
        </TabsContent>
        <TabsContent value="questions" className="mt-4">
          <OpenQuestions questions={analysis.openQuestions} />
        </TabsContent>
        <TabsContent value="email" className="mt-4">
          <EmailDraft email={email} onEmailChange={setEmail} />
        </TabsContent>
      </Tabs>
    </div>
  );
}
